[package]
name = "rust_todo_api"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing-subscriber = "0.3"
dashmap = "5"
